name = "DydxV3"
uuid = "aeb184e1-2eba-4dfa-950e-27d85795a490"
authors = ["Olivier Milla <olivier.milla@hey.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
